### ISSUE TITLE
Broken Pipe Exception

### ISSUE THREAD

**Issue by RootG** [kasirgalabs/Tilki#12]
I have seen that this exception causes clients to not receive their checksum codes, which causes the client application to stuck on 99% on upload stage. Issue must be investigated and resolved **ASAP**.

```
SEVERE: Error during session.
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at java.io.DataOutputStream.write(DataOutputStream.java:107)
	at java.io.DataOutputStream.writeUTF(DataOutputStream.java:401)
	at java.io.DataOutputStream.writeUTF(DataOutputStream.java:323)
	at kasirgalabs.FoxServiceThread.fileManager(FoxServiceThread.java:300)
	at kasirgalabs.FoxServiceThread.call(FoxServiceThread.java:71)
	at kasirgalabs.FoxServiceThread.call(FoxServiceThread.java:31)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by BaturayOnural** [comment]
How many users are effected from this on today ?

**Comment by RootG** [comment]
Around 20, not sure yet.

**Comment by BaturayOnural** [comment]
Huge problem, we should try to regenerate problem at the end of the upload stage by disconnecting from the connection.
If it is about the connection, it may be depending on the total count of users. (Don't know today's count but it was 59 on Saturday which is quite low.)

**Comment by RootG** [comment]
From my investigations this exception is raised when below situations happen:
- Heavy network traffic which causes clients to receive connection time out. (This is the main reason.)
- Client loses it's internet connection.
- Client application is crashed while sending file.

Decreasing simultaneous connection count might yield better results which is kind of a workaround.

The solution to this problem would be more scalable server architecture that able to handle heavy load and heavy I/O traffic.
