### ISSUE TITLE
Exception when starting video capture.

### ISSUE THREAD

**Issue by RootG** [kasirgalabs/Tilki#6]
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: java.lang.ref
lect.InvocationTargetException
        at com.teamdev.jxcapture.video.win.BaseDirectShowCapture.doStart(SourceF
ile:103)
        at com.teamdev.jxcapture.VideoCapture.start(SourceFile:146)
        at kasirgalabs.CaptureDesktop.StartCaptureDesktop(CaptureDesktop.java:50
)
        at kasirgalabs.MainClient.loginButtonMouseClicked(MainClient.java:553)
        at kasirgalabs.MainClient.access$500(MainClient.java:38)
        at kasirgalabs.MainClient$5.mouseClicked(MainClient.java:174)
        at java.awt.AWTEventMulticaster.mouseClicked(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
        at com.teamdev.jxdesktop.win32.g.doInvokeAndWait(Unknown Source)
        at com.teamdev.jxcapture.video.win.BaseDirectShowCapture.doStart(SourceF
ile:97)
        ... 37 more
Caused by: com.teamdev.jxdesktop.win32.com.ComException: COM object method retur
ns error code: 0xC00D0BB8;
        at com.teamdev.jxdesktop.win32.com.impl.IUnknownImpl.invokeStandardVirtu
alMethod(Unknown Source)
        at com.teamdev.jxdesktop.win32.com.impl.IUnknownImpl.invokeStandardVirtu
alMethod(Unknown Source)
        at com.teamdev.jxcapture.video.win.directshow.wrappers.impl.IMediaContro
lImpl.run(SourceFile:50)
        at com.teamdev.jxcapture.video.win.c.run(SourceFile:99)
        at com.teamdev.jxdesktop.win32.g$a.run(Unknown Source)
        at com.teamdev.jxdesktop.win32.g$c.run(Unknown Source)

**Comment by BaturayOnural** [comment]
Can you please specify the exception ? It seemed that you are trying to run 64 bit application on 32 bit operation system.

**Comment by RootG** [comment]
VirtualBox with a 64 bit Ubuntu and 64 bit Oracle JDK installed on it.

**Comment by BaturayOnural** [comment]
It is weird that there is so much mention about 32 bit windows system.

Caused by: com.teamdev.jxdesktop.win32.com.ComException: COM object method retur
ns error code: 0xC00D0BB8;
at com.teamdev.jxdesktop.win32.com.impl.IUnknownImpl.invokeStandardVirtu
alMethod(Unknown Source)
at com.teamdev.jxdesktop.win32.com.impl.IUnknownImpl.invokeStandardVirtu
alMethod(Unknown Source)
at com.teamdev.jxdesktop.win32.g$a.run(Unknown Source)
at com.teamdev.jxdesktop.win32.g$c.run(Unknown Source)

I believe that source of the problem is VirtualBox. We should re-generate 32 bit app and try it on this system.

**Comment by RootG** [comment]
I found a official post to a exception similar to this issue on [here](https://groups.google.com/a/teamdev.com/forum/#!searchin/jxcapture-forum/0xC00D0BB8%7Csort:relevance/jxcapture-forum/HkH0U8mdSl0/nQrYw-Z2G-MJ).

**Comment by RootG** [comment]
I am able to reproduce the same exception with a Windows 64 bit system installed Oracle JDK and Media Player Codec 4.3.8 on it. It seems that Media Player Codec 4.3.8 causes the exception because i do not get an exception when i remove it.

**Comment by RootG** [comment]
Trying to capture a screen with a resolution is not standard causes this exception. e.g. 1853x1024
